### PR TITLE
Add health attestation status codes

### PR DESCRIPTION
**Pull request by pl4nty**
New health attestation codes (6xx) [extracted from the Intune frontend](https://github.com/pl4nty/intune-change-tracking/blob/main/SettingStatusErrors.json)

### CODE REVIEW

**Comment by okieselbach** [comment]
Really nice, will include it in the next release. Nice work figuring it out via portal 👌

**Comment by okieselbach** [comment]
BTW, how did you find the URL https://afd-v2.hosting.portal.azure.net/

**Comment by pl4nty** [comment]
a fair bit of reverse engineering, not much I can share publicly though

**Review by okieselbach — APPROVED** [review]
New Status Codes for DHA

**Pull request merged**
